# Generated by Django 4.2.2 on 2023-06-14 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todo',
            name='title',
            field=models.CharField(default='Default Title', max_length=255),
        ),
    ]
